function getScssTheme(...path) {
  return `get-theme(${path.join(' , ')})`;
}

function getScssThemeColors(color) {
  return {
    default: getScssTheme('colors', color, 5),
    1: getScssTheme('colors', color, 1),
    2: getScssTheme('colors', color, 2),
    3: getScssTheme('colors', color, 3),
    4: getScssTheme('colors', color, 4),
    5: getScssTheme('colors', color, 5),
    6: getScssTheme('colors', color, 6),
    7: getScssTheme('colors', color, 7),
    8: getScssTheme('colors', color, 8),
    9: getScssTheme('colors', color, 9),
  };
}

module.exports = {
  prefix: '',
  important: false,
  separator: ':',
  theme: {
    colors: {
      transparent: 'transparent',

      black: '#10161A',
      white: '#fff',

      lighten: {
        1: 'rgba(255, 255, 255, 0.02)',
        2: 'rgba(255, 255, 255, 0.05)',
        3: 'rgba(255, 255, 255, 0.10)',
        4: 'rgba(255, 255, 255, 0.15)',
        5: 'rgba(255, 255, 255, 0.25)',
        6: 'rgba(255, 255, 255, 0.35)',
        7: 'rgba(255, 255, 255, 0.50)',
        8: 'rgba(255, 255, 255, 0.60)',
        9: 'rgba(255, 255, 255, 0.80)',
      },

      darken: {
        1: 'rgba(0, 0, 0, 0.03)',
        2: 'rgba(0, 0, 0, 0.06)',
        3: 'rgba(0, 0, 0, 0.10)',
        4: 'rgba(0, 0, 0, 0.15)',
        5: 'rgba(0, 0, 0, 0.25)',
        6: 'rgba(0, 0, 0, 0.35)',
        7: 'rgba(0, 0, 0, 0.50)',
        8: 'rgba(0, 0, 0, 0.60)',
        9: 'rgba(0, 0, 0, 0.80)',
      },

      gray: {
        1: '#f5f8fa',
        2: '#e1e8ed',
        3: '#ced9e0',
        4: '#bfccd6',
        5: '#A7B6C2',
        6: '#738694',
        7: '#394b59',
        8: '#293742',
        9: '#182026',
      },

      red: {
        1: '#fff5f5',
        2: '#fed7d7',
        3: '#feb2b2',
        4: '#fc8181',
        5: '#f56565',
        6: '#e53e3e',
        7: '#c53030',
        8: '#9b2c2c',
        9: '#742a2a',
      },

      orange: {
        1: '#fffaf0',
        2: '#feebc8',
        3: '#fbd38d',
        4: '#f6ad55',
        5: '#ed8936',
        6: '#dd6b20',
        7: '#c05621',
        8: '#9c4221',
        9: '#7b341e',
      },

      green: {
        1: '#f0fff4',
        2: '#c6f6d5',
        3: '#9ae6b4',
        4: '#68d391',
        5: '#48bb78',
        6: '#38a169',
        7: '#2f855a',
        8: '#276749',
        9: '#22543d',
      },

      blue: {
        1: '#ebf8ff',
        2: '#bee3f8',
        3: '#90cdf4',
        4: '#63b3ed',
        5: '#4299e1',
        6: '#3182ce',
        7: '#2b6cb0',
        8: '#2c5282',
        9: '#2a4365',
      },

      purple: {
        1: '#faf5ff',
        2: '#e9d8fd',
        3: '#d6bcfa',
        4: '#b794f4',
        5: '#9f7aea',
        6: '#805ad5',
        7: '#6b46c1',
        8: '#553c9a',
        9: '#44337a',
      },
    },
    spacing: {
      px: '1px',
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '8': '2rem',
      '10': '2.5rem',
      '12': '3rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '32': '8rem',
      '40': '10rem',
      '48': '12rem',
      '56': '14rem',
      '64': '16rem',
    },
    screens: {
      // sm: '640px',
      // md: '768px',
      lg: '1300px',
      // xl: '1280px',
    },
    fontFamily: {
      sans: [
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      mono: ['Menlo', 'Monaco', 'Consolas', '"Liberation Mono"', '"Courier New"', 'monospace'],
    },
    fontSize: {
      xs: getScssTheme('fontSize, xs'),
      sm: getScssTheme('fontSize', 'sm'),
      base: getScssTheme('fontSize', 'base'),
      lg: getScssTheme('fontSize', 'lg'),
      xl: getScssTheme('fontSize', 'xl'),
      '2xl': getScssTheme('fontSize', '2xl'),
      '3xl': getScssTheme('fontSize', '3xl'),
      '4xl': getScssTheme('fontSize', '4xl'),
      '5xl': getScssTheme('fontSize', '5xl'),
      '6xl': getScssTheme('fontSize', '6xl'),
    },
    fontWeight: {
      hairline: 100,
      thin: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900,
    },
    lineHeight: {
      none: 1,
      tight: 1.25,
      snug: 1.375,
      normal: 1.5,
      relaxed: 1.625,
      loose: 2,
    },
    letterSpacing: {
      tighter: '-.05em',
      tight: '-.025em',
      normal: '0',
      wide: '.025em',
      wider: '.05em',
      widest: '.1em',
    },
    textColor: theme => theme('colors'),
    backgroundColor: theme => theme('colors'),
    backgroundPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    backgroundSize: {
      auto: 'auto',
      cover: 'cover',
      contain: 'contain',
    },
    borderWidth: {
      default: '1px',
      '0': '0',
      '2': '2px',
      '4': '4px',
      '8': '8px',
    },
    borderColor: theme => ({
      ...theme('colors'),
      default: theme('colors').gray[300],
    }),
    borderRadius: {
      none: getScssTheme('borderRadius', 'none'),
      sm: getScssTheme('borderRadius', 'sm'),
      default: getScssTheme('borderRadius', 'default'),
      lg: getScssTheme('borderRadius', 'lg'),
      full: getScssTheme('borderRadius', 'full'),
    },
    cursor: {
      auto: 'auto',
      default: 'default',
      pointer: 'pointer',
      wait: 'wait',
      move: 'move',
      'not-allowed': 'not-allowed',
    },
    width: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.33333%',
      '2/3': '66.66667%',
      '1/4': '25%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.66667%',
      '5/6': '83.33333%',
      full: '100%',
      screen: '100vw',
    }),
    height: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      full: '100%',
      screen: '100vh',
    }),
    minWidth: {
      '0': '0',
      full: '100%',
    },
    minHeight: {
      '0': '0',
      full: '100%',
      screen: '100vh',
    },
    maxWidth: {
      xs: '20rem',
      sm: '24rem',
      md: '28rem',
      lg: '32rem',
      xl: '36rem',
      '2xl': '42rem',
      '3xl': '48rem',
      '4xl': '56rem',
      '5xl': '64rem',
      '6xl': '72rem',
      full: '100%',
    },
    maxHeight: {
      full: '100%',
      screen: '100vh',
    },
    padding: theme => theme('spacing'),
    margin: theme => ({ auto: 'auto', ...theme('spacing') }),
    negativeMargin: theme => theme('spacing'),
    objectPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    boxShadow: {
      default: getScssTheme('boxShadow', 'default'),
      md: getScssTheme('boxShadow', 'md'),
      lg: getScssTheme('boxShadow', 'lg'),
      inner: getScssTheme('boxShadow', 'inner'),
      outline: getScssTheme('boxShadow', 'outline'),
      none: getScssTheme('boxShadow', 'none'),
    },
    zIndex: {
      auto: 'auto',
      '0': 0,
      '10': 10,
      '20': 20,
      '30': 30,
      '40': 40,
      '50': 50,
    },
    opacity: {
      '0': '0',
      '25': '.25',
      '50': '.5',
      '75': '.75',
      '100': '1',
    },
    fill: {
      current: 'currentColor',
    },
    stroke: {
      current: 'currentColor',
    },
    flex: {
      '1': '1 1 0%',
      auto: '1 1 auto',
      initial: '0 1 auto',
      none: 'none',
    },
    flexGrow: {
      '0': 0,
      default: 1,
    },
    flexShrink: {
      '0': 0,
      default: 1,
    },
    listStyleType: {
      none: 'none',
      disc: 'disc',
      decimal: 'decimal',
    },
    inset: {
      '0': 0,
      auto: 'auto',
    },
    container: {},
  },
  variants: {
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: ['hover', 'focus', 'dark'],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: ['hover', 'focus', 'dark'],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    cursor: [],
    display: ['responsive'],
    flexDirection: [],
    flexWrap: [],
    alignItems: [],
    alignSelf: [],
    justifyContent: [],
    alignContent: [],
    flex: [],
    flexGrow: [],
    flexShrink: [],
    float: [],
    fontFamily: [],
    fontWeight: ['hover', 'focus'],
    height: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    negativeMargin: [],
    objectFit: [],
    objectPosition: [],
    opacity: ['hover', 'focus'],
    outline: ['focus'],
    overflow: [],
    padding: [],
    pointerEvents: [],
    position: [],
    inset: [],
    resize: [],
    boxShadow: ['hover', 'focus', 'dark'],
    fill: [],
    stroke: [],
    tableLayout: [],
    textAlign: [],
    textColor: ['hover', 'focus', 'dark'],
    fontSize: [],
    fontStyle: [],
    textTransform: [],
    textDecoration: ['hover', 'focus'],
    fontSmoothing: [],
    letterSpacing: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    wordBreak: [],
    width: [],
    zIndex: [],
  },
  corePlugins: {},
  plugins: [
    function({ addUtilities, addComponents, addVariant, e, prefix, config }) {
      addVariant('dark', ({ modifySelectors, separator, container }) => {
        container.walkRules(rule => {
          rule.selector = `.${process.env.BLUEPRINT_NAMESPACE || 'bp3'}-dark .${e(
            `dark${separator}${rule.selector.slice(1)}`
          )}`;
        });
      });
    },
  ],
};
