import { ITableOfContentsLink } from '../../TableOfContents';

export const studioContents: ITableOfContentsLink[] = [
  {
    name: 'Introduction',
    depth: 0,
    type: 'item',
    to: '/docs/introduction.md',
  },
  {
    name: 'UI Overview',
    depth: 0,
    type: 'item',
    to: '/docs/ui-overview.md',
  },
  {
    name: 'Markdown',
    depth: 0,
    type: 'divider',
  },
  {
    name: 'Markdown Basics',
    depth: 0,
    type: 'item',
    to: '/docs/markdown/basic-syntax.md',
  },
  {
    name: 'Stoplight Flavored Markdown (SMD)',
    depth: 0,
    type: 'item',
    to: '/docs/markdown/stoplight-flavored-markdown.md',
  },
  {
    name: 'Swagger Petstore',
    depth: 0,
    type: 'divider',
  },
  {
    name: 'Overview',
    depth: 0,
    type: 'item',
    to: '/reference/petstore/openapi.v1.yaml',
  },
  {
    name: 'Pets',
    depth: 0,
    type: 'group',
  },
  {
    name: 'Pets',
    depth: 1,
    type: 'item',
    to: '/reference/petstore/openapi.v1.yaml/components/schemas/Pets',
  },
  {
    name: 'Info for a specific pet [active item]',
    depth: 1,
    type: 'item',
    to: '/reference/petstore/openapi.v1.yaml/paths/~1pets~1{petId}/get',
    isActive: true,
  },
  {
    name: 'List all pets',
    depth: 1,
    type: 'item',
    to: '/reference/petstore/openapi.v1.yaml/paths/~1pets/get',
  },
  {
    name: 'Create a pet',
    depth: 1,
    type: 'item',
    to: '/reference/petstore/openapi.v1.yaml/paths/~1pets/post',
  },
  {
    name: 'To-dos',
    depth: 0,
    type: 'divider',
  },
  {
    name: 'Overview',
    depth: 0,
    type: 'item',
    to: '/reference/todos/openapi.v1.json',
  },
  {
    name: 'Todos',
    depth: 0,
    type: 'group',
  },
  {
    name: 'Delete Todo',
    depth: 1,
    type: 'item',
    to: '/reference/todos/openapi.v1.json/paths/~1todos~1{todoId}/delete',
  },
  {
    name: 'Get Todo',
    depth: 1,
    type: 'item',
    to: '/reference/todos/openapi.v1.json/paths/~1todos~1{todoId}/get',
  },
  {
    name: 'Update Todo',
    depth: 1,
    type: 'item',
    to: '/reference/todos/openapi.v1.json/paths/~1todos~1{todoId}/put',
  },
  {
    name: 'List Todos',
    depth: 1,
    type: 'item',
    to: '/reference/todos/openapi.v1.json/paths/~1todos/get',
  },
  {
    name: 'Create Todo',
    depth: 1,
    type: 'item',
    to: '/reference/todos/openapi.v1.json/paths/~1todos/post',
  },
  {
    name: 'Models',
    depth: 0,
    type: 'divider',
  },
  {
    name: 'Category',
    to: '/reference/petstore/models/category.v1.yaml',
    depth: 0,
    type: 'item',
  },
  {
    name: 'Error',
    to: '/reference/common/models/error.v1.yaml',
    depth: 0,
    type: 'item',
  },
  {
    name: 'Pet',
    to: '/reference/petstore/models/pet.v1.yaml',
    depth: 0,
    type: 'item',
  },
  {
    name: 'Todo Full',
    to: '/reference/todos/models/todo-full.v1.json',
    depth: 0,
    type: 'item',
  },
  {
    name: 'Todo Partial',
    to: '/reference/todos/models/todo-partial.v1.json',
    depth: 0,
    type: 'item',
  },
  {
    name: 'User',
    to: '/reference/todos/models/user.v1.json',
    depth: 0,
    type: 'item',
  },
];
